### ISSUE TITLE
v3.12.1 seems to crash abruptly and is stuck only displaying the black screen without loading the next startup menu

### ISSUE THREAD

**Issue by FruitsPunchParfaits34** [chrislo27/RhythmHeavenRemixEditor#250] opened 2018-07-20 13:53 UTC
### Information
**Log file**: 
[log_2018-07-20_22-16-06.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/2214104/log_2018-07-20_22-16-06.txt)

**Editor version**: v3.12.1

### Description
The v3.11.0 (and now recent v3.12.1) version of RHRE doesn't seem to be working for my Macbook Air (13-inch, Mid 2012). I tried multiple times trying to re-download the patch, also downloaded the latest Java update (Version 8 Update 171) but that doesn't seem to fix it.

Every time though I load the jar. file, it brings up the black screen like it would normally, although now the screen remains black and won't load the next start-up screen for some reason. 

Also, every time I try and the close the browser I have to force-quit the screen as just simply clicking the red X button just soft-locks the 'Jar Launcher' screen. (This isn't too problematic, but it's just an noteworthy observation. I just need essential help with the above)

Overall, I have absolutely NO clue why this is happening now or how I'm supposed to fix it as previous updates and versions have worked perfectly fine beforehand and for whatever reason it just doesn't want to work now. So I please request some assistance in getting the latest RHRE patch to function properly for future custom remixes. Thanks in advance.

https://imgur.com/oJoxOBk (Screenshot of the 'freezing/crashing black screen' issue)

### Behaviours
**Expected behaviour**: The program would load like normal and begin loading sound files.

**Actual behaviour**: The window just stayed black and did not progress to the loading bar.

**Comment by chrislo27** [comment] 2018-07-20 14:42
From the log file you've uploaded, you have tried running v3.12.0 and/or v3.12.1, but are running v3.8.0. Please upload a log file from running in v3.12.1.

(The current error in the log file is that you tried to load a v3.12.0 SFX database in v3.8.0, and it's complaining about Bossa Nova having multiple copies of its objects, which is a change that did happen in v3.12.0.)

**Comment by chrislo27** [comment] 2018-07-20 22:34
I don't know what your problem is. You have given me an unhelpful log file which doesn't tell me anything about the underlying problem.

Please read each comment carefully: again, please give me a **log file from running in v3.12.1**. I will close this issue if you cannot do your part to help with this problem.

**Comment by FruitsPunchParfaits34** [comment] 2018-07-21 01:37
How do I specifically extract the log file from the Jar. file?

**Comment by chrislo27** [comment] 2018-07-21 01:41
It's the same way you got the first log file.

1. Run v3.12.1. If it loads properly, great -- say so and we can finish up. If not, close the program and find the most recent log file by:
2. Navigating to `~/.rhre3/logs/` and getting the most recent log file. Make sure the time stamp on the file name is correct for the time that you ran the editor. Upload the log file here as a comment.
3. I'll analyze the log file and see what we can do from there.

**Comment by FruitsPunchParfaits34** [comment] 2018-07-21 01:46
[log_2018-07-21_11-42-13.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/2215803/log_2018-07-21_11-42-13.txt)

Here you go. I think this should be the most recent log file. Hope this helps.

**Comment by chrislo27** [comment] 2018-07-21 02:07
[Please try and test this special version of v3.12.1.](https://send.firefox.com/download/0596bd80cf/#dlnwxI1uphIPomtFLSTXTw) Make a copy of your original RHRE3.jar, and then replace the existing one with the one in the link.

You only have 24 hours to download this file (it will expire).

Please comment back on whether it is a) fixed or b) not fixed. If it is not fixed, comment with a new log file from **this version**.

**Comment by FruitsPunchParfaits34** [comment] 2018-07-21 03:39
It unfortunately didn't work either. Sorry.

[log_2018-07-21_13-36-34.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/2215857/log_2018-07-21_13-36-34.txt)

**Comment by chrislo27** [comment] 2018-07-21 03:41
Please delete this folder and try again.
`/var/folders/6y/cdp99czs2dj52s_mfs3rcb5801xkt_/T/jna-1451407557`

**Comment by FruitsPunchParfaits34** [comment] 2018-07-21 03:55
I searched the folder but it appeared empty. I deleted it anyway and relaunched the jar file but it still isn't working.

[log_2018-07-21_13-51-26.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/2215865/log_2018-07-21_13-51-26.txt)

**Comment by chrislo27** [comment] 2018-07-21 04:21
Alright, I've looked at the difference between v3.8.0 and v3.11.0+ to try to see if there's any specific change that may have triggered this. I think I *may* have found the issue, but to verify, I'm going to have to ask you to test this.

Again, if it works -- you can keep that version (it's identical to v3.12.1 with your fix) and I'll make sure all future versions have this fix from now on. Otherwise, repeat the log file process.

[Link to Firefox Send file](https://send.firefox.com/download/75a9383719/#V38OWBn3uPhu7WIJ36M-vg)

Thank you for being patient and cooperative during this. I know it's always frustrating to see a bug with a totally unknown root cause.

**Comment by FruitsPunchParfaits34** [comment] 2018-07-21 04:34
No worries, I've been trying to get this working for a few weeks now and if this process is helping with addressing and testing bugs and inconsistencies in the files, then so be it, I'll try and help out.

The test2 file also doesn't work either, but I'll send the next log file in for you. 

[log_2018-07-21_14-30-56.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/2215893/log_2018-07-21_14-30-56.txt)

**Comment by chrislo27** [comment] 2018-07-21 04:37
To reiterate: this only started happened ON v3.11.0 or v3.9.0? This is really important as there's a significant dependency difference between the two versions that I could try to isolate.

**Comment by FruitsPunchParfaits34** [comment] 2018-07-21 04:45
After using v3.8.0 (which is now deleted) for a while and just now deciding to update to latest version at the time = v3.11.0, this issue started to appear, even though previous updates have worked fine in the past. 

So I think it is v3.11.0 that had brought this issue to the forefront, though I am not sure as I haven't updated to v3.9.0 and just now tried updating to the latest version.

**Comment by chrislo27** [comment] 2018-07-21 04:53
I'm starting to run out of ideas here. I'm going to give you test3 which has a rolled back version of a certain dependency I use.

The issue is that in v3.8.0, this dependency didn't exist. It's hard to say if the error is caused by this certain dependency suddenly existing in v3.9.0+, it having a different version in v3.11.0, or if this is entirely unrelated. 

[Firefox Send](https://send.firefox.com/download/522a584083/#e3Z-Z9ZN2Q0GEFV90DYGPg)

Same procedure as usual. If this one fails, I might try to remove this dependency and see (though that will be some code mangling).

**Comment by chrislo27** [comment] 2018-07-21 04:54
Actually, if you could also try [v3.9.1](https://github.com/chrislo27/RhythmHeavenRemixEditor/releases/tag/v3.9.1) it would be helpful. The SFX won't work but the startup error is what's important.

**Comment by FruitsPunchParfaits34** [comment] 2018-07-21 05:31
v3.9.1 is also not running either. 

Also, I'd like to send the log file for v3.9.1, except it's not appearing in the log folder like the previous files for some reason.

**Comment by chrislo27** [comment] 2018-07-21 05:33
(v3.9.1 log files are stored next to the jar file, but no need)

Unfortunately this looks to be an error caused by the Discord integration, but with an unknown solution. I have been looking for quite a while now, and the *only* issue I can find that is similar is this one: https://github.com/AllTheMods/ATM-3/issues/382

You may notice that its error is virtually the same as in your log files. They resolved their issue by removing the Minecraft mod that had the Discord integration in it.

Removing this integration is not an option for me. However, one big similarity I noticed between this issue and the other is that the OS (operating system) version is the same: Mac OS X 10.10.5. As far as I can tell through analytical data, you are my only 10.10.X user. Every other Mac user has at least 10.11.X or higher.

I suspect this has something to do with the underlying operating system version, since I contacted a few other users who did use macOS and they have no issues. They all have a higher OS version though.

This is a really big request, but perhaps updating to [OS X El Capitan](https://en.wikipedia.org/wiki/OS_X_El_Capitan) will do the trick. You noted that you have a MacBook Air from Mid-2012, and it seems based on the Wikipedia page for El Capitan that your model of MacBook is supported.

I understand if you do not want to (or cannot) update to this OS version. I apologize for the inconveniences caused, but it may be in your best interests overall to do the update.

**Comment by FruitsPunchParfaits34** [comment] 2018-07-21 05:46
It's alright. I already greatly appreciate your assistance in helping me sort out the various issues and bugs with the latest versions and I hope that at some point that you can fix the difficult issues in the near future. 

I'll take your advice however and try and update to OS X El Capitan (10.11.2) and just see if that does the trick. It does seem that having a higher OS ver. is the key to running the latest updates so we'll see what comes up when I finally do update my Mac. I'll report here back to you for further updates/advice if the process either goes well or not. 

Again, thanks so much for your support and wish you the best of luck for future updates.

**Comment by chrislo27** [comment] 2018-07-21 05:51
Thank you.

I'll leave this issue open for a little while so you can comment if necessary.

**Closed** 2018-07-28 23:21 UTC
Labels: cantfix, internal
