### ISSUE TITLE
Bizarre Cue Stacking Glitch

### ISSUE THREAD

**Issue by iRonnoc5** [chrislo27/RhythmHeavenRemixEditor#207] opened 2017-10-08 05:16 UTC
### Information
**Log File**:
[log_2017-10-06_22-08-42.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/1366633/log_2017-10-06_22-08-42.txt)

**Editor version**: v3.4.0

### Description
If you place down one cue, and then drag another cue anywhere on top of it, and then hit the spacebar (to play the track), the cues will play on top of each other as long as you're holding down the click to keep your highlighted cue over the other cue. Once you let go of the click, the cue is reset to its original position (or gets deleted if the cue is right out of the cue selection box), even if the song is still playing.

### Behaviours
**Expected behaviour**: If you drag the cue on top of the other, and then you press play while keeping the highlighted cue over the other, the cue should disappear/reset to its original position like it would if you were to place one cue on top of another under other circumstances.

**Actual behaviour**: Instead, if you hold down the mouse click to keep the cue on top of the other, and then hit the spacebar to play the song, the cues will just play over each other.

**Comment by chrislo27** [comment] 2017-10-08 05:19
Would a better intended behaviour be to alternatively not allow playback while dragging? (It would be easier to write.) 

Thank you for the feedback!

**Comment by chrislo27** [comment] 2017-10-08 17:15
This has been fixed as of commit 78d90187cfc8fefc0ee3af4d285ae5f922881db9. Because this is a non-critical bug, the next release will not be soon.

**Closed** 2017-10-29 21:26 UTC
Labels: bug, fixed
